pipeline:
  templates:
    image: composer:latest
    commands:
      - scripts/build_templates.sh
  sass:
    image: node:6.9.5
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm install -g webpack
      - npm install
      - webpack
  build:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/ktbartholomew/teambicyclesinc
    tags:
    - "latest"
    - "${DRONE_COMMIT_SHA}"
    secrets:
    - docker_username
    - docker_password
    when:
      branch: master
      event: [push, tag, deployment]
  publish:
    image: quay.io/ktbartholomew/teambicyclesinc:latest
    pull: true
    secrets:
    - aws_key
    - aws_secret
    - acf_key
    commands:
    - RELEASE=latest /publish.sh
    - RELEASE=${DRONE_COMMIT_SHA} /publish.sh
