version: '3'
services:
  db:
    image: mysql:5.7
    networks:
      - teambicyclesinc
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    image: tbi-wordpress
    networks:
      - teambicyclesinc
    environment:
      - GOOGLE_CALENDAR_ID=teambikesinc@gmail.com
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ACF_KEY=${ACF_KEY}
    ports:
      - 8080:80
    volumes:
      - ./test/wp-config.php:/var/www/html/wp-config.php
      - ./dist/:/var/www/html/wp-content/themes/theme
      - wp-uploads:/var/www/html/wp-content/uploads

networks:
  teambicyclesinc:

volumes:
  mysql-data:
  wp-uploads:
