version: '3'
services:
  db:
    image: mysql:5.7
    networks:
      - teambicyclesinc
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    image: quay.io/ktbartholomew/teambicyclesinc
    networks:
      - teambicyclesinc
    environment:
      - DEBUG=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ACF_KEY=${ACF_KEY}
    ports:
      - 8080:80
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./dist/:/var/www/html/wp-content/themes/theme
      - wp-uploads:/var/www/html/wp-content/uploads

networks:
  teambicyclesinc:

volumes:
  mysql-data:
  wp-uploads:
