apiVersion: v1
kind: Secret
metadata:
  namespace: teambicyclesinc
  name: mysql-password
type: Opaque
data:
  username: $(echo -n "${DB_USER}" | base64)
  password: $(echo -n "${DB_PASSWORD}" | base64)
