apiVersion: v1
kind: Service
metadata:
  namespace: teambicyclesinc
  name: cache
spec:
  selector:
    app: teambicyclesinc
    role: cache
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: teambicyclesinc
  name: wordpress
spec:
  selector:
    app: teambicyclesinc
    role: wordpress
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teambicyclesinc
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: nfs-internal.kubernetes.keithbartholomew.com
    path: /exports/share/teambicyclesinc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: teambicyclesinc
  name: teambicyclesinc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: teambicyclesinc
  name: cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teambicyclesinc
        role: cache
    spec:
      containers:
      - name: cache
        image: nginx
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: proxy-cache.conf
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: teambicyclesinc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: teambicyclesinc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: teambicyclesinc
        role: wordpress
    spec:
      containers:
      - name: wordpress
        image: quay.io/ktbartholomew/teambicyclesinc
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db_password
        - name: DB_HOST
          value: mysql-internal.kubernetes.keithbartholomew.com
        - name: GOOGLE_CALENDAR_ID
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: google_calendar_id
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: google_api_key
        - name: ACF_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: acf_key
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: auth_key
        - name: SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: secure_auth_key
        - name: LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: logged_in_key
        - name: NONCE_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: nonce_key
        - name: AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: auth_salt
        - name: SECURE_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: secure_auth_salt
        - name: LOGGED_IN_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: logged_in_salt
        - name: NONCE_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: nonce_salt
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: wp-uploads
          mountPath: /var/www/html/wp-content/uploads
          subPath: wp-uploads
        resources:
          limits:
            memory: "400Mi"
      volumes:
      - name: wp-uploads
        persistentVolumeClaim:
          claimName: teambicyclesinc
