apiVersion: v1
kind: Namespace
metadata:
  name: teambicyclesinc
---
apiVersion: v1
kind: Service
metadata:
  namespace: teambicyclesinc
  name: mysql
spec:
  selector:
    app: teambicyclesinc
    role: db
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  namespace: teambicyclesinc
  name: wordpress
spec:
  selector:
    app: teambicyclesinc
    role: wordpress
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: teambicyclesinc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teambicyclesinc
        role: db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db_name
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: "0.3"
            memory: "200Mi"
      volumes:
      - name: mysql-data
        hostPath:
          path: /mnt/gv0/teambicyclesinc/mysql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: teambicyclesinc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teambicyclesinc
        role: wordpress
    spec:
      containers:
      - name: wordpress
        image: quay.io/ktbartholomew/teambicyclesinc
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db_password
        - name: DB_HOST
          value: mysql.teambicyclesinc.svc.cluster.local
        - name: GOOGLE_CALENDAR_ID
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: google_calendar_id
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: google_api_key
        - name: ACF_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: acf_key
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: auth_key
        - name: SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: secure_auth_key
        - name: LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: logged_in_key
        - name: NONCE_KEY
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: nonce_key
        - name: AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: auth_salt
        - name: SECURE_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: secure_auth_salt
        - name: LOGGED_IN_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: logged_in_salt
        - name: NONCE_SALT
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: nonce_salt
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: wp-uploads
          mountPath: /var/www/html/wp-content/uploads
        resources:
          limits:
            cpu: "0.6"
            memory: "100Mi"
      volumes:
      - name: wp-uploads
        hostPath:
          path: /mnt/gv0/teambicyclesinc/wp-uploads
