apiVersion: v1
kind: Secret
metadata:
  namespace: teambicyclesinc
  name: wordpress-secrets
type: Opaque
data:
  db_name: $(echo -n "${DB_NAME}" | base64)
  db_user: $(echo -n "${DB_USER}" | base64)
  db_password: $(echo -n "${DB_PASSWORD}" | base64)
  google_calendar_id: $(echo -n "${GOOGLE_CALENDAR_ID}" | base64)
  google_api_key: $(echo -n "${GOOGLE_API_KEY}" | base64)
  acf_key: $(echo -n "${ACF_KEY}" | base64)
  auth_key: $(echo -n "${AUTH_KEY}" | base64)
  secure_auth_key: $(echo -n "${SECURE_AUTH_KEY}" | base64)
  logged_in_key: $(echo -n "${LOGGED_IN_KEY}" | base64)
  nonce_key: $(echo -n "${NONCE_KEY}" | base64)
  auth_salt: $(echo -n "${AUTH_SALT}" | base64)
  secure_auth_salt: $(echo -n "${SECURE_AUTH_SALT}" | base64)
  logged_in_salt: $(echo -n "${LOGGED_IN_SALT}" | base64)
  nonce_salt: $(echo -n "${NONCE_SALT}" | base64)
